name: The Aoc owen

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
  run_solutions:
    strategy:
      matrix:
        os: [ubuntu-latest]
        year: [2022, 2023, 2024]
        day: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
        include:
          - os: windows-latest
          - year: 2024
          - day: 1

    runs-on: ${{ matrix.os }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      - id: check_folder
        name: Check solution presence
        run: |
          if [ -d "${{ matrix.year }}/${{ matrix.day }}" ]; then
            echo "sol_exist=YES" >> $GITHUB_OUTPUT
          else
            echo "sol_exist=NO" >> $GITHUB_OUTPUT
          fi

      - id: step2
        name: Install aoc-cli binary
        if: steps.check_folder.outputs.sol_exist == 'YES'
        run: |
          cd /tmp
          curl -sSL https://github.com/scarvalhojr/aoc-cli/releases/download/0.12.0/aoc-cli-0.12.0-x86_64-unknown-linux-musl.tar.gz -o aoc-cli.tar.gz
          tar -xzf aoc-cli.tar.gz
          mv aoc-cli-0.12.0-x86_64-unknown-linux-musl/aoc /usr/local/bin/aoc-cli
          which aoc-cli
          aoc-cli --version

      - id: step3
        name: Get input
        if: steps.step2.conclusion == 'success'
        run: |
          cd ${{ matrix.year }}/${{ matrix.day }} 
          aoc-cli -y ${{ matrix.year }} -d ${{ matrix.day }} -I download
          ls -lai
        env:
          ADVENT_OF_CODE_SESSION: ${{ secrets.ADVENT_OF_CODE_SESSION }}

      - id: step4
        name: Run the solution
        if: steps.step3.conclusion == 'success'
        run: |
          cd ${{ matrix.year }}/${{ matrix.day }} 
          wc -l input
          make test

          