name: The Aoc owen

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
  run_solutions:
    strategy:
      matrix:
        os: [ubuntu-latest]
        year: [2022, 2023, 2024]
        day: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
        include:
          - os: windows-latest
          - year: 2024
          - day: 1

    runs-on: ${{ matrix.os }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      - id: check_folder_lnx
        name: Check solution presence on linux
        if: runner.os == 'Linux'
        run: |
          if [ -d "${{ matrix.year }}/${{ matrix.day }}" ]; then
            echo "sol_exist=YES" >> $GITHUB_OUTPUT
          else
            echo "sol_exist=NO" >> $GITHUB_OUTPUT
          fi

      - id: check_folder_win
        name: Check solution presence on windows
        if: runner.os == 'Windows'
        run: |
          if (Test-Path "${{ matrix.year }}\${{ matrix.day }}") {
              echo "sol_exist=YES" >> $env:GITHUB_OUTPUT
          } else {
              echo "sol_exist=NO" >> $env:GITHUB_OUTPUT
          }

      - id: install_aoc_win
        name: Install aoc-cli binary
        if: steps.check_folder_win.outputs.sol_exist == 'YES'
        run: |
          cd $env:TEMP
          Invoke-WebRequest -Uri https://github.com/scarvalhojr/aoc-cli/releases/download/0.12.0/aoc-cli-0.12.0-x86_64-pc-windows-msvc.zip -OutFile aoc-cli.zip
          Expand-Archive -Path aoc-cli.zip -DestinationPath aoc-cli
          Move-Item -Path aoc-cli\aoc.exe -Destination $env:ProgramFiles\aoc-cli.exe
          aoc-cli --version

      - id: install_aoc_lnx
        name: Install aoc-cli binary
        if: steps.check_folder_lnx.outputs.sol_exist == 'YES'
        run: |
          cd /tmp
          curl -sSL https://github.com/scarvalhojr/aoc-cli/releases/download/0.12.0/aoc-cli-0.12.0-x86_64-unknown-linux-musl.tar.gz -o aoc-cli.tar.gz
          tar -xzf aoc-cli.tar.gz
          mv aoc-cli-0.12.0-x86_64-unknown-linux-musl/aoc /usr/local/bin/aoc-cli
          aoc-cli --version

      - id: step3
        name: Get input
        if: steps.install_aoc_lnx.conclusion == 'success' || steps.install_aoc_win.conclusion == 'success'
        run: |
          cd ${{ matrix.year }}/${{ matrix.day }} 
          aoc-cli -y ${{ matrix.year }} -d ${{ matrix.day }} -I download
        env:
          ADVENT_OF_CODE_SESSION: ${{ secrets.ADVENT_OF_CODE_SESSION }}

      - id: step4
        name: Run the test
        if: steps.step3.conclusion == 'success'
        run: |
          cd ${{ matrix.year }}/${{ matrix.day }} 
          make test
